

menu:
    main:
        - name: Work
          url: /work/
          weight: 30
        - name: Articles
          url: /articles/
          weight: 20
        - name: Talks
          url: /Talks/
          weight: 15

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Haimantika


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Haimantika Mitra
        description: |

          Hello, I am Haimantika.
          Professionally, I am a Developer Advocate. I excel at technical writing,developer experience, building with GenAI, and frontend. I also wrote an eBook on "How to DevRel for Startups", that you can read on [learn.haimantika.com](https://learn.haimantika.com/).

        

          
        imageUrl: "/images/hm.png"
        imageTitle: pic
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Newsletter
              url: https://haimantika.substack.com?sd=pf
    mainSections:
      - articles

    socialIcons:
        - name: twitter
          url: "https://twitter.com/HaimantikaM"
        - name: github
          url: "https://github.com/Haimantika"
        - name: linkedin
          url: "https://www.linkedin.com/in/haimantika-mitra/"
        - name: hashnode
          url: "https://haimantika.dev/blog"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

