

menu:
    main:
        - name: Work
          url: /work/
          weight: 30
        - name: Articles
          url: /articles/
          weight: 20
        - name: Talks
          url: /Talks/
          weight: 15

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Haimantika


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Haimantika Mitra
        description: |

          Hello, I am Haimantika.
          Currently working as a Developer Advocate at Hashnode. I help B2D+ companies bridge the gap between developers and the product with code, content and community. As a community builder and a product of the community myself, I strongly believe that technology is for everyone. I am passionate about learning, sharing, and building with the community.
        

          
        imageUrl: "/images/hm.png"
        imageTitle: pic
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Newsletter
              url: https://haimantika.substack.com?sd=pf
    mainSections:
      - articles

    socialIcons:
        - name: twitter
          url: "https://twitter.com/HaimantikaM"
        - name: github
          url: "https://github.com/Haimantika"
        - name: linkedin
          url: "https://www.linkedin.com/in/haimantika-mitra/"
        - name: hashnode
          url: "https://haimantika.dev/blog"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

